// RobGo-RG stereo: ESP32 WROVER, VGA da TTGO VGA32 v1.4.
#define RG_TARGET_NAME "RobGo-RG"
#define RG_STORAGE_ROOT "/sd"
#define RG_STORAGE_SDSPI_HOST SPI2_HOST
#define RG_STORAGE_SDSPI_SPEED SDMMC_FREQ_PROBING
#define RG_GPIO_SDSPI_CS GPIO_NUM_13
#define RG_GPIO_SDSPI_MOSI GPIO_NUM_12
#define RG_GPIO_SDSPI_CLK GPIO_NUM_14
#define RG_GPIO_SDSPI_MISO GPIO_NUM_2
#define RG_AUDIO_USE_INT_DAC 1
#define RG_AUDIO_INT_DAC_STEREO 0
#define RG_AUDIO_USE_EXT_DAC 0
#define RG_SCREEN_DRIVER 2
#define RG_SCREEN_WIDTH 320
#define RG_SCREEN_HEIGHT 240
#define RG_SCREEN_ROTATE 0
#define RG_SCREEN_BACKLIGHT 0
#define RG_SCREEN_VISIBLE_AREA {0, 0, 0, 0}
#define RG_SCREEN_SAFE_AREA {0, 0, 0, 0}
#define RG_GPIO_VGA_R0 GPIO_NUM_22
#define RG_GPIO_VGA_R1 GPIO_NUM_21
#define RG_GPIO_VGA_G0 GPIO_NUM_19
#define RG_GPIO_VGA_G1 GPIO_NUM_18
#define RG_GPIO_VGA_B0 GPIO_NUM_5
#define RG_GPIO_VGA_B1 GPIO_NUM_4
#define RG_GPIO_VGA_HSYNC GPIO_NUM_23
#define RG_GPIO_VGA_VSYNC GPIO_NUM_15
#define RG_GPIO_KBD_DATA GPIO_NUM_27
#define RG_GPIO_KBD_CLK GPIO_NUM_26
#define RG_GPIO_MOUSE_DATA GPIO_NUM_32
#define RG_GPIO_MOUSE_CLK GPIO_NUM_33
// GPIO36 não possui pull-up interno. Botão considerado ativo em nível baixo.
#define RG_GAMEPAD_GPIO_MAP {{RG_KEY_MENU, .num=GPIO_NUM_36, .pullup=0, .level=0},}
#define RG_BATTERY_DRIVER 0
#define RG_UPDATER_ENABLE 0

// Versao de uso normal: sem logs periodicos do monitor de sistema.
#define RG_QUIET_PERIODIC_LOGS 1

